# Python 이미지를 기반으로 시작합니다.
FROM python:3.9-slim

# 작업 디렉토리 설정
WORKDIR /app

# Python 애플리케이션을 컨테이너에 복사
COPY . /app

# 필요한 Python 패키지를 설치합니다.
RUN pip install --no-cache-dir streamlit

# kubectl과 git 설치
RUN apt-get update && \
    apt-get install -y curl git && \
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    chmod +x ./kubectl && \
    mv ./kubectl /usr/local/bin/kubectl

# krew 설치
RUN set -x; cd "$(mktemp -d)" && \
    OS="$(uname | tr '[:upper:]' '[:lower:]')" && \
    ARCH="$(uname -m)" && \
    if [ "$ARCH" = "aarch64" ]; then ARCH="arm64"; fi && \
    KREW="krew-${OS}_${ARCH}" && \
    curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" && \
    tar zxvf "${KREW}.tar.gz" && \
    KREW_ROOT="/root/.krew" ./krew-"${OS}_${ARCH}" install krew

# PATH 환경 변수에 krew 설치 경로 추가
ENV PATH="/root/.krew/bin:$PATH"

# kubectl node-shell 플러그인 설치
RUN kubectl krew install node-shell

# 컨테이너가 시작될 때 실행될 명령어 설정
CMD ["streamlit", "run", "your_script.py", "--server.port=8501", "--server.address=0.0.0.0"]
